"""
sql_validator.py — Safety layer that ensures only SELECT queries execute.

Blocks all data-modifying or schema-altering SQL statements before
they reach the database. This is the critical security gate between
the AI-generated SQL and the actual database connection.
"""
import re
from typing import Tuple


# ── Blocked keyword patterns (case-insensitive word-boundary matches) ──────
_BLOCKED_PATTERNS = [
    r"\bDELETE\b",
    r"\bUPDATE\b",
    r"\bINSERT\b",
    r"\bDROP\b",
    r"\bALTER\b",
    r"\bTRUNCATE\b",
    r"\bCREATE\b",
    r"\bGRANT\b",
    r"\bREVOKE\b",
    r"\bEXEC\b",
    r"\bEXECUTE\b",
    r"\bCALL\b",
    r"\bMERGE\b",
    r"\bREPLACE\b",
    r"\bLOAD\s+DATA\b",
    r"\bSHUTDOWN\b",
    r"\bSET\s+GLOBAL\b",
    r"\bSET\s+SESSION\b",
    r"\bSHOW\s+GRANTS\b",
    r"\bINTO\s+OUTFILE\b",
    r"\bINTO\s+DUMPFILE\b",
]

_COMPILED_BLOCKED = [re.compile(p, re.IGNORECASE) for p in _BLOCKED_PATTERNS]


def validate_sql(sql: str) -> Tuple[bool, str]:
    """
    Validate that a SQL string is a safe SELECT query.

    Args:
        sql: The SQL string generated by the AI.

    Returns:
        (is_valid, error_message)
        - (True,  "")        → safe to execute
        - (False, "CANNOT_ANSWER") → AI could not generate SQL for this question
        - (False, "<reason>") → blocked for security reasons
    """
    if not sql or not sql.strip():
        return False, "The AI did not return a SQL query."

    stripped = sql.strip()

    # Special sentinel value from the AI
    if stripped.upper() == "CANNOT_ANSWER":
        return False, "CANNOT_ANSWER"

    # ── Step 1: Remove comments before analysis ────────────────────────────
    clean = _remove_comments(stripped)

    # ── Step 2: Check for blocked keywords ────────────────────────────────
    for pattern in _COMPILED_BLOCKED:
        match = pattern.search(clean)
        if match:
            keyword = match.group(0)
            return (
                False,
                f"Blocked: '{keyword.upper()}' is not allowed. "
                f"Only SELECT queries are permitted."
            )

    # ── Step 3: Must start with SELECT ────────────────────────────────────
    first_word = clean.split()[0].upper() if clean.split() else ""
    if first_word != "SELECT":
        return (
            False,
            f"Blocked: Query must start with SELECT. "
            f"Got: '{first_word}'. Only SELECT statements are allowed."
        )

    # ── Step 4: No multiple statements (prevents chained injection) ────────
    # Split on semicolons; ignore trailing empty string from final semicolon
    statements = [s.strip() for s in clean.split(";") if s.strip()]
    if len(statements) > 1:
        return (
            False,
            "Blocked: Multiple SQL statements are not allowed. "
            "Only a single SELECT query is permitted per request."
        )

    return True, ""


def _remove_comments(sql: str) -> str:
    """Strip SQL comments so blocked keywords inside comments aren't flagged."""
    # Remove block comments: /* ... */
    sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
    # Remove line comments: -- ...
    sql = re.sub(r"--[^\r\n]*", " ", sql)
    # Remove hash comments: # ...
    sql = re.sub(r"#[^\r\n]*", " ", sql)
    return sql.strip()
